### ISSUE TITLE
Is it working with comments ?

### ISSUE THREAD

**Issue by PhanDuc** [abhay1/django-facebook-messenger-bot-tutorial#2]
Hi abhay !

I read your post, its very awesome and help me understand webhooks. 
After this your post i have an question, 
How to make this project work with comments and if i want to save all news even to db how i can do that's ?

Thanks so much Abhay !

**Comment by hayabhay** [comment]
You will have to familiarize yourself with Django models and create a table for what you want to store. Then you can use the conversation to capture and store the user content
