### ISSUE TITLE
Can't get user name

### ISSUE THREAD

**Issue by BlueFRJ** [abhay1/django-facebook-messenger-bot-tutorial#3]
Hi!
When I run the code, it works fine until I send a message to the bot, when I get this error:

> joke_text = 'Yo '+user_details['first_name']+'..!' + joke_text
> KeyError: 'first_name'

And facebook returns this:

```
> {u'error': {u'message': u'Invalid OAuth access token.', u'code': 190, u'type': u'OAuthException', u'fbtrace_id': u'HcT2M7LgPTY'}}
> {u'error': {u'code': 100,
>             u'error_subcode': 2018001,
>             u'fbtrace_id': u'ANUjQzx/PUi',
>             u'message': u'(#100) No matching user found',
>             u'type': u'OAuthException'}}
```

So, I don't know what to do know, as user's name is really important for my idea.
Thanks in advice

**Comment by Nielssie** [comment]
You have to set the value for PAGE_ACCESS_TOKEN =
