### ISSUE TITLE
I am trying to implement your application but it gives me error in importing 4 modules.

### ISSUE THREAD

**Issue by likbz** [abhay1/django-facebook-messenger-bot-tutorial#6]
fbbot/views.py", line 4, in <module>
    import json, requests, random, re
ImportError: No module named 'requests'
Can you solve this?

**Comment by hayabhay** [comment]
You should install requests. If you've downloaded the contents of the repository, you can find "pip install -r requirements.txt" in the list of commands that you have to run. This will install requests.

**Comment by likbz** [comment]
I have connected your application and interacts with facebook, but the chat application does not return any answers, I have dedicated this afternoon but I have been a long time with this error, just as you can give me a solution.
This is the message that returns me, the code is just as I have changed the tokens.

fbbot/views.py", line 73, in post
    post_facebook_message(message['sender']['id'], message['message']['text'])
/fbbot/views.py", line 39, in post_facebook_message
    joke_text = 'Yo '+user_details['first_name']+'..! ' + joke_text
KeyError: 'first_name
